### ISSUE TITLE
Possible modifications or aids for the user

### ISSUE THREAD

**Issue by Ivalize** [microgenomics/tutorials#3]
Hi. 
I really appreciate the tutorial. I did it and appreciate some modifications or missing data, which would improve it. I hope its not obvious information~

In the part of " Determining the Pangenome" and "roary_plots" you show core alignment tree but the program only provide the accessory (at least of me) and you need to executed "FastTree –nt –gtr core_gene_alignment.aln > core_alignment.newick" to obtained and plot it.
Other, in the part of " Pangenome sequence analysis" the name of python script is DBGenerator.py and the command line above say ...GeneratorDB.py.. this provide a mistake to execute the script and maybe some people do not notice it.

Thanks for all.

**Comment by Katterinne** [comment]
Hello!

Thank you for considering our tutorial and for help us to improve it!

You're right, roary only provide one tree `accessory_binary_genes.fa.newick` based on the presence and absence of the accessory genes in the isolates's genomes, which is not a reliable tree, it’s made just to have an idea of how the isolates are grouped based on their accessory genome. Roary is not a program to infer a phylogenetic tree, so in order to use the python script `roary_plots.py` you should previously have a phylogeny that represent the evolutive history of your isolates or, as you say, use the core gene alignment (file: `core_gene_alignment.aln`, through the `-e` parameter) as input to infer a tree.

About the “DBGenerator.py” script, yes this is clearly a typing mistake.

We added a link to download the phylogeny used in the tutorial and correct the typing error.

For more details about roary https://sanger-pathogens.github.io/Roary/

**Thank you** for your help!

**Comment by Ivalize** [comment]
De nada!
